
image: macos

environment:
    R_VERSION: 3.6.1
    HEADERS_LOCATION: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk
    MACOSX_DEPLOYMENT_TARGET: 10.11

install:
  - curl -o R.tar.gz https://cloud.r-project.org/src/base/R-3/R-$R_VERSION.tar.gz
  - tar xf R.tar.gz
  - curl -o clang.pkg https://cloud.r-project.org/bin/macosx/tools/clang-7.0.0.pkg
  - sudo installer -pkg clang.pkg -target /
  - curl -o gfortran.pkg https://cloud.r-project.org/bin/macosx/tools/gfortran-6.1.pkg
  - sudo installer -pkg gfortran.pkg -target /
  - curl -o pcre.tar.gz https://mac.r-project.org/libs/pcre-8.40-darwin.15-x86_64.tar.gz
  - tar xf pcre.tar.gz
  - curl -o cairo.tar.gz https://mac.r-project.org/libs/cairo-1.14.2-darwin.13-x86_64.tar.gz
  - tar xf cairo.tar.gz
#  - curl -o cairomm.tar.gz https://mac.r-project.org/libs/cairomm-1.11.2-darwin.13-x86_64.tar.gz
#  - tar xf cairomm.tar.gz
  - curl -o libpng.tar.gz https://mac.r-project.org/libs/libpng-1.6.28-darwin.15-x86_64.tar.gz
  - tar xf libpng.tar.gz
  - curl -o jpeg.tar.gz https://mac.r-project.org/libs/jpeg-9-darwin.15-x86_64.tar.gz
  - tar xf jpeg.tar.gz
#  - curl -o tiff.tar.gz https://mac.r-project.org/libs/tiff-4.0.7-darwin.15-x86_64.tar.gz
#  - tar xf tiff.tar.gz
#  - curl -o xz.tar.gz https://mac.r-project.org/libs/xz-5.2.3-darwin.15-x86_64.tar.gz
#  - tar xf xz.tar.gz
  - sudo ditto usr/local /usr/local
  - pkg-config --version
  - ls /usr/local/lib/pkgconfig
  - pkg-config --exists cairo-png

build_script:
  #- ls /usr/local/clang7/bin
  #- export CC=/usr/local/clang7/bin/clang
  #- export CXX=/usr/local/clang7/bin/clang++
  #- export CPP=/usr/local/clang7/bin/clang-cpp
  #- export CFLAGS="-isysroot $HEADERS_LOCATION"
  #- export CCFLAGS="-isysroot $HEADERS_LOCATION"
  #- export CXXFLAGS="-isysroot $HEADERS_LOCATION"
  #- export CPPFLAGS="-isysroot $HEADERS_LOCATION -I/usr/local/include"
  - export FC=/usr/local/gfortran/bin/gfortran
  #- export SHLIB_CXXLDFLAGS="-Wl,-rpath,\${R_HOME}/lib \${R_HOME}/lib/libc++abi.1.dylib"
  #- export SHLIB_CXX14LDFLAGS="-Wl,-rpath,\${R_HOME}/lib \${R_HOME}/lib/libc++abi.1.dylib"
  - cd R-$R_VERSION
  - ./configure --enable-R-framework --enable-R-shlib --with-aqua=no --with-tcltk=no --with-x=no --with-cairo=yes --with-libpng=yes --with-jpeglib=yes --with-libtiff=yes
  - make
  - sudo make install
  - cd ..
  - ditto /Library/Frameworks/R.framework R.framework
  - /Library/Frameworks/R.framework/Resources/bin/R -e "install.packages(c('Rcpp', 'RInside'), repos='https://cloud.r-project.org', lib='R.framework/Resources/library', type='mac.binary.el-capitan')"
  - mkdir R.framework/Resources/site-library
  - /Library/Frameworks/R.framework/Resources/bin/R -e "install.packages(c('rjson', 'base64enc', 'RProtoBuf', 'knitr', 'testthat', 'rlang', 'ggplot2', 'remotes'), repos='https://cloud.r-project.org', lib='R.framework/Resources/site-library', type='mac.binary.el-capitan')"
  - python patch-framework.py

artifacts:
  - name: R framework
    path: R.framework.tar.bz2
