
image: macos

environment:
    R_VERSION: 3.6.1

install:
  - curl -o R.tar.gz https://cloud.r-project.org/src/base/R-3/R-$R_VERSION.tar.gz
  - tar xf R.tar.gz
  - curl -o clang.pkg https://cloud.r-project.org/bin/macosx/tools/clang-7.0.0.pkg
  - sudo installer -pkg clang.pkg -target /
  - curl -o gfortran.pkg https://cloud.r-project.org/bin/macosx/tools/gfortran-6.1.pkg
  - sudo installer -pkg gfortran.pkg -target /

build_script:
  - export PATH=$PATH:/usr/local/gfortran/bin
  - cd R-$R_VERSION
  - ./configure --enable-R-framework --enable-R-shlib --with-aqua=no --with-tcltk=no --with-x=no --with-cairo --with-libpng --with-jpeglib --with-libtiff
