
image: macos

environment:
    R_VERSION: 3.6.1
    R_TOOLS_URL: https://github.com/rmacoslib/r-macos-rtools/releases/download/v3.2.2/macos-rtools-3.2.2.pkg

install:
  - curl -o R.tar.gz https://cloud.r-project.org/src/base/R-3/R-$R_VERSION.tar.gz
  - tar xf R.tar.gz
  - curl -o clang.pkg https://cran.r-project.org/bin/macosx/tools/clang-8.0.0.pkg
  - ls
  - sudo installer -pkg clang.pkg -target /


build_script:
  - cd R-$R_VERSION
  - ./configure --enable-R-framework --enable-R-shlib --with-aqua=no --with-tcltk=no --with-x=no --with-cairo --with-libpng --with-jpeglib --with-libtiff
