
image: macos

environment:
    R_VERSION: 3.6.1

install:
  - curl -o R.tar.gz https://cloud.r-project.org/src/base/R-3/R-$R_VERSION.tar.gz
  - tar xf R.tar.gz

build:
  - cd R-$R_VERSION
  - ./configure --enable-R-framework --enable-R-shlib --with-aqua=no --with-tcltk=no --with-x=no --with-cairo --with-libpng --with-jpeglib --with-libtiff
