
image: macos

environment:
    R_URL: https://cloud.r-project.org/src/base/R-3/R-3.6.1.tar.gz

install:
  - curl -O R.tar.gz https://cloud.r-project.org/src/base/R-3/R-3.6.1.tar.gz
  - tar xf R.tar.gz
  - ls
