
image: macos

environment:
    R_VERSION: 3.6.1
    HEADERS_LOCATION: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk

install:
  - curl -o R.tar.gz https://cloud.r-project.org/src/base/R-3/R-$R_VERSION.tar.gz
  - tar xf R.tar.gz
  - curl -o clang.pkg https://cloud.r-project.org/bin/macosx/tools/clang-7.0.0.pkg
  - sudo installer -pkg clang.pkg -target /
  - curl -o gfortran.pkg https://cloud.r-project.org/bin/macosx/tools/gfortran-6.1.pkg
  - sudo installer -pkg gfortran.pkg -target /
  - curl -o pcre.tar.gz https://mac.r-project.org/libs/pcre-8.40-darwin.15-x86_64.tar.gz
  - tar xf pcre.tar.gz
  - curl -o cairo.tar.gz https://mac.r-project.org/libs/cairo-1.14.2-darwin.13-x86_64.tar.gz
  - tar xf cairo.tar.gz
  - curl -o libpng.tar.gz https://mac.r-project.org/libs/libpng-1.6.28-darwin.15-x86_64.tar.gz
  - tar xf libpng.tar.gz
  - sudo ditto usr/local /usr/local
  - ls /usr/local/clang7/bin

build_script:
  - export PATH=$PATH:/usr/local/gfortran/bin
  - export CC=/usr/local/clang7/bin/clang
  - export CXX=/usr/local/clang7/bin/clang++
  - export CFLAGS="-isysroot $HEADERS_LOCATION"
  - export CCFLAGS="-isysroot $HEADERS_LOCATION"
  - export CXXFLAGS="-isysroot $HEADERS_LOCATION"
  - export CPPFLAGS="-isysroot $HEADERS_LOCATION -I/usr/local/include"
  - cd R-$R_VERSION
  - ./configure --help
  - "./configure --enable-R-framework --enable-R-shlib --with-aqua=no --with-tcltk=no --with-x=no --with-cairo=yes --with-libpng=yes --with-jpeglib=yes --with-libtiff=yes || true"

artifacts:
  - name: logs
    path: *.log
