
image: macos

environment:
    R_VERSION: 3.6.1
    MACOSX_DEPLOYMENT_TARGET: 10.11
    CRAN_MIRROR: https://cran.microsoft.com/snapshot/2020-01-01

install:
  - curl -o clang.pkg https://cloud.r-project.org/bin/macosx/tools/clang-7.0.0.pkg
  - sudo installer -pkg clang.pkg -target /
  - curl -o gfortran.pkg https://cloud.r-project.org/bin/macosx/tools/gfortran-6.1.pkg
  - sudo installer -pkg gfortran.pkg -target /
  - curl -o XQuartz.pkg https://www.jamovi.org/misc/XQuartz.pkg
  - sudo installer -package XQuartz.pkg -target /
  - curl https://cloud.r-project.org/src/base/R-3/R-$R_VERSION.tar.gz | tar xz
  - curl https://mac.r-project.org/libs/pcre-8.40-darwin.15-x86_64.tar.gz | tar xz
  - curl https://mac.r-project.org/libs/pixman-0.32.6-darwin.13-x86_64.tar.gz | tar xz
  - curl https://mac.r-project.org/libs/fontconfig-2.11.1-darwin.13-x86_64.tar.gz | tar xz
  - curl https://mac.r-project.org/libs/freetype-2.5.5-darwin.13-x86_64.tar.gz | tar xz
  - curl https://mac.r-project.org/libs/cairo-1.14.2-darwin.13-x86_64.tar.gz | tar xz
  - curl https://mac.r-project.org/libs/libpng-1.6.28-darwin.15-x86_64.tar.gz | tar xz
  - curl https://mac.r-project.org/libs/jpeg-9-darwin.15-x86_64.tar.gz | tar xz
  - curl https://mac.r-project.org/libs/tiff-4.0.7-darwin.15-x86_64.tar.gz | tar xz
  - curl https://mac.r-project.org/libs/readline-5.2-12-darwin8-bin4.tar.gz | tar xz
  - sudo ditto usr/local /usr/local

build_script:

  - export PATH=/usr/local/clang7/bin:/usr/local/gfortran/bin/gfortran:$PATH

  - cd R-$R_VERSION
  
  - cat configure | grep -v "#include <cairo-xlib.h>" >tmp
  - cat tmp >configure
  - rm tmp
  
  - ./configure --enable-R-framework --enable-R-shlib --with-aqua=no --with-tcltk=no --with-x=no --with-cairo=yes --with-libpng=yes --with-jpeglib=yes --with-libtiff=yes
  - make
  - sudo make install
  - cd ..
  
  - ditto /Library/Frameworks/R.framework R.framework
  - /Library/Frameworks/R.framework/Resources/bin/R -e "install.packages(c('Rcpp', 'RInside'), repos='$CRAN_MIRROR', lib='R.framework/Resources/library', type='source')"
  - mkdir -p R.framework/Resources/base
  - mkdir -p R.framework/Resources/base/R
  - /Library/Frameworks/R.framework/Resources/bin/R -e "install.packages(c('rjson', 'base64enc', 'RProtoBuf', 'knitr', 'testthat', 'rlang', 'ggplot2', 'remotes'), repos='$CRAN_MIRROR', lib='R.framework/Resources/base/R', type='mac.binary.el-capitan')"
  - python patch-framework.py
  - mv R.framework/Resources/base .
  
  - echo "#!/bin/sh"                              >tmp
  - echo "# Shell wrapper for R executable."      >>tmp
  - echo HERE=\$\(cd \"\$\(dirname \"\$0\"\)\"\; pwd\) >>tmp
  - echo export R_HOME=\$HERE/..                  >>tmp
  - echo export R_SHARE_DIR=\$R_HOME/share        >>tmp
  - echo export R_INCLUDE_DIR=\$R_HOME/include    >>tmp
  - echo export R_DOC_DIR=\$R_HOME/doc            >>tmp
  - tail -n +41 R.framework/Versions/Current/Resources/bin/R >>tmp
  - cat tmp >R.framework/Versions/Current/Resources/bin/R
  - rm tmp
  
  - tar -cjf R.framework.tar.bz2  R.framework
  - tar -cjf base.tar.bz2         base

artifacts:
  - name: R framework
    path: R.framework.tar.bz2
  - name: Base module
    path: base.tar.bz2
